name: "ImageCreation"
title: "图片摄影创作"
mode: "dev"
port: 4001
version: "v0.0.1"

log:
  level: "debug"
  filename: "ImageCreation.log"
  max_size: 200
  max_age: 30
  max_backips: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "lide123."
  dbname: "imagecreation"
  max_open_conns: 200
  max_idle_conns: "50"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 5
  pool_size: 100

email:
  user: "1019528265@qq.com"
  pass: "umiueaxacsknbbig"
  host: "smtp.qq.com"
  port: 465
  rename: "ImageCreation"

apiKeys:
  - "6ZUUwUDCk_woNQeTa08uok7E67XdTMuJXzNRNkNC2gQ"
  - "soSfySaTOOCDbT4c6x2uAtHT9vAv_vcREfaHMUm5TG8"
  - "bdGWF-_MVxtzgiHv2V6PSSD_mDu9Ga88NRWYDABHU74"
  - "VhKv_iprwfuhUru9sL7MrE8iAOqo9iCzU6OyYQp1xAM"
  - "js1UEyCaFesf3B66Ie7WPxQpWIStlhLRPh2dgriP1uo"
  - "TtVo04sWt-bL2CDFagV46b7ZtXP-_LfGrkSd4q8a2RM"
  - "8dws2jf0LMNW4pd573pC582cvuN0QH6h2hTk8z41SYc"
  - "OHc2ydJXgBs1klbPC8kspt3PrswLpEs0n-qBflwsZzw"
  - "xflPjF7W10dlu3ajhPXK4_IeW5flUyfxb3yfRmM1WfQ"
  - "B4dTWWYOFcnwTlYYWDJb8ZhnF8hAqsl5RXa_KVhENrM"